server:
  port: 9527

spring:
  application:
    name: springcloud-zuul


#Rureka的配置，服务地址
eureka:
  client:
    service-url:
      #单机注册http://localhost:7001/eureka/
      #集群发布：https://eureka7001.com:7001/eureka/，https://eureka7002.com:7002/eureka/，https://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true


info:
  app.name: zhang-springcloud
  company.name: blog.zhang.com


# zull 路由网关配置
zuul:
  # 路由相关配置
  # 原来访问路由 eg:http://www.cspStudy.com:9527/springcloud-provider-dept/dept/get/1
  # zull路由配置后访问路由 eg:http://www.cspstudy.com:9527/haust/mydept/dept/get/1
  routes:
    mydept.serviceId: springcloud-procider-dept # eureka注册中心的服务提供方路由名称
    mydept.path: /mydept/** # 将eureka注册中心的服务提供方路由名称 改为自定义路由名称

  # 不能再使用这个路径访问了，*： 忽略,隐藏全部的服务名称~
  ignored-services: "*"  #隐藏全部的
  # 设置公共的前缀
  prefix: /zhang  #http://www.zhang.com:9527/zhang/mydept/dept/get/1
