server:
  port: 7001

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #将localhost 换成 自己定义的eureka7001.com ==localhost 的意思  #Eureka 服务端的实例名字
  client:
    register-with-eureka: false #表示是否向Eureka注册中心注册自己
    fetch-registry: false # fetch-registry 如果为false， 则表示自己为注册中心
    service-url: #监控界面
      #      动态编写服务地址和接口
      #单机https://${eureka.instance.hostname}:${server.port}/eureka/
      #集群：是要挂载其他的eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

