server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: eureka7003.com #Eureka 服务端的实例名字
  client:
    register-with-eureka: false #表示是否向Eureka注册中心注册自己
    fetch-registry: false # fetch-registry 如果为false， 则表示自己为注册中心
    service-url: #监控界面
      #      动态编写服务地址和接口
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

